### ISSUE TITLE
Failed to compile with newest mq MQ2-20130918

### ISSUE THREAD

**Issue by mickevi** [brainiac/MQ2Py#3]
I get this error when I try to compile mq2py:;

> MQ2PyExt_Item.cpp(86): error C2039: 'Item' : is not a member of 'EQData::_CONTENTS'
> 1>          e:\chrome_downloads\mq2-20130821\mq2main\EQData.h(637) : see declaration of 'EQData::_CONTENTS'
> 1>MQ2PyExt_Item.cpp(101): error C2039: 'EvolvingLoreGroup' : is not a member of 'EQData::_CONTENTS'
> 1>          e:\chrome_downloads\mq2-20130821\mq2main\EQData.h(637) : see declaration of 'EQData::_CONTENTS'
> 1>MQ2PyExt_Item.cpp(171): warning C4244: 'return' : conversion from 'DWORD' to 'float', possible loss of data

**Comment by brainiac** [comment]
3 years later.. now builds with latest zip
